
management:
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey
  endpoint:
    chaosmonkey:
      enabled: true


chaos:
  monkey:
    enabled: true
    assaults:
      level: 5
      latencyRangeStart: 1000
      latencyRangeEnd: 7000
    watcher:
      component: false
      controller: false
      repository: false
      restController: false
      service: true
